name = "rifasnuevo"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "rifasv2"
database_id = "c9c7e308-6c71-49f9-8eff-7f80512d7dc0"

[env.production.vars]
JWT_SECRET = "clave_temporal_cambiar_con_secret_put"
ADMIN_PASSWORD = "admin123_cambiar_con_secret_put"