name = "rifa-puntos-prod"
compatibility_date = "2025-12-16"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "rifasv2"
database_id = "c9c7e308-6c71-49f9-8eff-7f80512d7dc0"

[env.production.vars]
JWT_SECRET = "cambiar_esta_clave_en_produccion_123456"
ADMIN_PASSWORD = "admin123"