name = "rifa-puntos-prod"
compatibility_date = "2025-12-17"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "rifasv2"
database_id = "c9c7e308-6c71-49f9-8eff-7f80512d7dc0"

[env.production]
compatibility_date = "2025-12-17"

[env.production.vars]
JWT_SECRET = "tu_clave_secreta_jwt_cambiar_en_produccion"
ADMIN_PASSWORD = "admin123" # Cambiar esto en producci√≥n